### ISSUE TITLE
Add multilevel structure example

### ISSUE THREAD

**Issue by pilot** [itemsapi/dashboard#8]
simple and ofter to use categories structure like:

- category
 - sub category
- category
- category
 - sub category
 - sub category

**Comment by cigolpl** [comment]
Do you mean object structure for showing in the table:
![selection_376](https://cloud.githubusercontent.com/assets/1032493/11591916/a507e118-9a9b-11e5-8f59-823c9284d560.png)

Or mapping example with object fields ?

**Comment by pilot** [comment]
![image](https://cloud.githubusercontent.com/assets/28564/11591981/875741fa-9aa4-11e5-905f-c8c538df9d59.png)

this is usual case

**Comment by cigolpl** [comment]
Thanks for example. I don't think it will work with the current API version but it is definitely good use case for some requirements (i.e. ecommerce !?)

I am thinking about the implementation and wondering how to store data that elasticsearch will be aware that `sub1` and `sub2` are 'children' of `category` ?

`parent field` - 
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-parent-field.html ?

**Comment by pilot** [comment]
not only for ecommerce, but for any calogue contain system, like a sales aggregation page

there is example of mapping for nested field from real project

```yml
variants:
                            type: "nested"
                            properties:
                                id:
                                    type: "integer"
                                status:
                                    type: "boolean"
                                prices:
                                    type: "nested"
                                    properties:
                                        value:
                                            type: "integer"
                                        oldValue:
                                            type: "integer"
                                        currencyCode:
                                            type: "string"
                                options:
                                    type: "nested"
                                    properties:
                                        id:
                                            type: "integer"
                                        value:
                                            type: "string"
                                            index: not_analyzed
                                        minSize:
                                            type: "integer"
                                        maxSize:
                                            type: "integer"
```
